# Data Categories

The data is seperated in these categories; 
 
`ResponseId | MainBranch | Employment | RemoteWork| EdLevel| YearsCode | OrgSize | Country | Age | Gender | Trans | Sexuality | Ethnicity | Accessibility | MentalHealth | WorkExp | ConvertedCompYearly | C# | C | HTML/CSS,
  | Python | Dart | Bash/Shell | JavaScript | Java | Haskell | Assembly | Go | Groovy | Crystal | PHP | Delphi | C++ | Clojure | Kotlin | APL | Rust | TypeScript | COBOL | PowerShell | Scala | Elixir | F# | LISP | Ruby | Julia | MATLAB | Objective-C | Erlang | Swift | Fortran | OCaml | R | SQL | Perl | Lua | VBA`
  
Our Inputs for the model are;

`MainBranch | Employment | RemoteWork| EdLevel| YearsCode | OrgSize | Country | Age | Gender | Trans | Sexuality | Ethnicity | Accessibility | MentalHealth | WorkExp | C# | C | HTML/CSS,
  | Python | Dart | Bash/Shell | JavaScript | Java | Haskell | Assembly | Go | Groovy | Crystal | PHP | Delphi | C++ | Clojure | Kotlin | APL | Rust | TypeScript | COBOL | PowerShell | Scala | Elixir | F# | LISP | Ruby | Julia | MATLAB | Objective-C | Erlang | Swift | Fortran | OCaml | R | SQL | Perl | Lua | VBA`
  
Our Outputs for the model will be;

`ConvertedCompYearly`

# Importing data and libraries

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle as pkl

sns.set()

from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score, train_test_split, KFold, GridSearchCV
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from sklearn import metrics
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.metrics import confusion_matrix, classification_report

In [26]:
df = pd.read_csv("CleanedData.csv")
df

,Unnamed: 0,ResponseId,MainBranch,Employment,RemoteWork,EdLevel,YearsCode,OrgSize,Country,Age,...,Objective-C,Erlang,Swift,Fortran,OCaml,R,SQL,Perl,Lua,VBA
0,11,12,1,1,1,1,3,1,1,1,...,0,0,0,0,0,0,1,0,0,0
1,12,13,2,2,2,1,3,2,1,2,...,0,0,1,0,0,0,1,0,0,0
2,14,15,2,1,1,2,3,3,1,2,...,0,0,0,0,0,1,0,0,0,0
3,21,22,2,2,2,2,2,1,2,2,...,0,0,0,0,0,0,1,0,0,0
4,22,23,2,2,1,3,4,4,3,1,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21285,73110,73111,2,2,1,1,3,1,3,2,...,0,0,0,0,0,0,0,0,0,0
21286,73112,73113,2,2,2,1,2,5,24,2,...,0,0,0,0,0,0,0,0,0,0
21287,73113,73114,2,2,1,2,2,5,1,2,...,0,0,0,0,0,0,0,0,0,0
21288,73116,73117,2,2,2,1,4,9,1,1,...,0,0,0,0,0,0,0,0,0,0
21289,73119,73120,2,2,2,1,2,3,1,2,...,0,0,0,0,0,0,1,0,0,0

In [27]:
df['ConvertedCompYearly']

0        194400
1         65000
2        110000
3         34126
4         97605
          ...
21285     60906
21286     52255
21287     94000
21288    115000
21289     70000
Name: ConvertedCompYearly, Length: 21290, dtype: int64

# Define Input and Output

In [28]:
# Input data 
X = df[['MainBranch','Employment','RemoteWork','EdLevel','YearsCode','OrgSize','Country','Age','Gender','Trans','Sexuality','Ethnicity','Accessibility','MentalHealth','WorkExp','C#','C','HTML/CSS','Python','Dart','Bash/Shell','JavaScript','Java','Haskell','Assembly','Go','Groovy','Crystal','PHP','Delphi','C++','Clojure','Kotlin','APL','Rust','TypeScript','COBOL','PowerShell','Scala','Elixir','F#','LISP','Ruby','Julia','MATLAB','Objective-C','Erlang','Swift','Fortran','OCaml','R','SQL','Perl','Lua','VBA']]


# Output data 
y = df["ConvertedCompYearly"]

X = np.asarray(X).astype('float32')
y = np.asarray(y).astype('float32')



# Split data into training and test sets, 70% and 30%.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Modeling

In [29]:
from sklearn.linear_model import Ridge,Lasso,RidgeCV,LassoCV,ElasticNet,ElasticNetCV,LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn import neighbors
from sklearn.svm import SVR

## Chosing a model we will use

In [30]:
knn=KNeighborsRegressor().fit(X_train,y_train)
ada=AdaBoostRegressor().fit(X_train,y_train)
svm=SVR().fit(X_train,y_train)
ridge=Ridge().fit(X_train,y_train)
lasso=Lasso().fit(X_train,y_train)
rf=RandomForestRegressor().fit(X_train,y_train)
gbm=GradientBoostingRegressor().fit(X_train,y_train)

models=[ridge,lasso,knn,ada,svm,rf,gbm]

def ML(Y,models):
    y_pred=models.predict(X_test)
    mse=mean_squared_error(y_test,y_pred)
    rmse=np.sqrt(mean_squared_error(y_test,y_pred))
    r2=r2_score(y_test,y_pred)*100
    
    return mse,rmse,r2

for i in models:
    print("\n",i,"\n\nDifferent models success rate :",ML("salary_in_usd",i))

 Ridge()

Different models success rate : (2915611400.0, 53996.402, 31.50089755331422)

 Lasso()

Different models success rate : (2915583700.0, 53996.145, 31.501543773719508)

 KNeighborsRegressor()

Different models success rate : (2811935700.0, 53027.688, 33.93664183164407)

 AdaBoostRegressor()

Different models success rate : (3101140710.063481, 55687.88656488484, 27.142084727573756)

 SVR()

Different models success rate : (4523520650.681129, 67257.12341961355, -6.275179075524662)

 RandomForestRegressor()

Different models success rate : (2338465461.723893, 48357.68255121303, 45.06030702673698)

 GradientBoostingRegressor()

Different models success rate : (2238842622.366861, 47316.409652116046, 47.40083687290594)

## Let's experiment with columns

In [53]:
# Input data 
#X = df[['MainBranch','Employment','RemoteWork','EdLevel','YearsCode','OrgSize','Country','Age','Gender','Trans','Sexuality','Ethnicity','Accessibility','MentalHealth','WorkExp','C#','C','HTML/CSS','Python','Dart','Bash/Shell','JavaScript','Java','Haskell','Assembly','Go','Groovy','Crystal','PHP','Delphi','C++','Clojure','Kotlin','APL','Rust','TypeScript','COBOL','PowerShell','Scala','Elixir','F#','LISP','Ruby','Julia','MATLAB','Objective-C','Erlang','Swift','Fortran','OCaml','R','SQL','Perl','Lua','VBA']]
#X = df[['MainBranch','Employment','RemoteWork','EdLevel','YearsCode','OrgSize','Country','Age','Gender','Trans','Sexuality','Ethnicity','Accessibility','MentalHealth','WorkExp']]
#X = df[['Employment','RemoteWork','EdLevel','YearsCode','OrgSize','Country','Age','Gender','Trans','Sexuality','Ethnicity','Accessibility','WorkExp','C#','C','HTML/CSS','Python','Dart','Bash/Shell','JavaScript','Java','Haskell','Assembly','Go','Groovy','Crystal','PHP','Delphi','C++','Clojure','Kotlin','APL','Rust','TypeScript','COBOL','PowerShell','Scala','Elixir','F#','LISP','Ruby','Julia','MATLAB','Objective-C','Erlang','Swift','Fortran','OCaml','R','SQL','Perl','Lua','VBA']]
X = df[['MainBranch','Employment','RemoteWork','EdLevel','YearsCode','OrgSize','Country','Age','Gender','Trans','Sexuality','Ethnicity','Accessibility','WorkExp','C#','C','HTML/CSS','Python','Dart','Bash/Shell','JavaScript','Java','Haskell','Assembly','Go','Groovy','Crystal','PHP','Delphi','C++','Clojure','Kotlin','APL','Rust','TypeScript','COBOL','PowerShell','Scala','Elixir','F#','LISP','Ruby','Julia','MATLAB','Objective-C','Erlang','Swift','Fortran','OCaml','R','SQL','Perl','Lua','VBA']]

# Output data 
y = df["ConvertedCompYearly"]

X = np.asarray(X).astype('float32')
y = np.asarray(y).astype('float32')


#rebalance using SMOTE
#from imblearn.over_sampling import SMOTE

#smote = SMOTE(random_state=42)
#X, y = smote.fit_resample(X, y)

# Split data into training and test sets, 70% and 30%.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)



# without 'mentalhealth'- 47.68%
# without 'mentalhealth' and 'accesability'- 47.59%

In [54]:
knn=KNeighborsRegressor().fit(X_train,y_train)
ada=AdaBoostRegressor().fit(X_train,y_train)
svm=SVR().fit(X_train,y_train)
ridge=Ridge().fit(X_train,y_train)
lasso=Lasso().fit(X_train,y_train)
rf=RandomForestRegressor().fit(X_train,y_train)
gbm=GradientBoostingRegressor().fit(X_train,y_train)

models=[ridge,lasso,knn,ada,svm,rf,gbm]

def ML(Y,models):
    y_pred=models.predict(X_test)
    mse=mean_squared_error(y_test,y_pred)
    rmse=np.sqrt(mean_squared_error(y_test,y_pred))
    r2=r2_score(y_test,y_pred)*100
    
    return mse,rmse,r2

for i in models:
    print("\n",i,"\n\nDifferent models success rate :",ML("salary_in_usd",i))

 Ridge()

Different models success rate : (2915181800.0, 53992.42, 31.510982631782113)

 Lasso()

Different models success rate : (2915150600.0, 53992.133, 31.511717032693408)

 KNeighborsRegressor()

Different models success rate : (2706900700.0, 52027.883, 36.404326024739355)

 AdaBoostRegressor()

Different models success rate : (3073575412.5449905, 55439.83597148345, 27.78970129800028)

 SVR()

Different models success rate : (4521711950.634707, 67243.67591554396, -6.232685642605662)

 RandomForestRegressor()

Different models success rate : (2338848001.136531, 48361.63770114212, 45.05131968087942)

 GradientBoostingRegressor()

Different models success rate : (2226804188.89659, 47189.02614905917, 47.683666724174365)